In [16]:
import requests
import pandas as pd
from bs4 import BeautifulSoup as bs4
all_links=[]
URL="https://www.mykhel.com/cricket/most-expensive-player-in-ipl-2022-auction-full-list-of-highest-paid-players-184026.html"
    
data=requests.get(URL)
data=data.content

data=bs4(data,"html5lib")
data=data.find_all(class_="oi_cms_table")

In [17]:
data=data[0].text.split("\n")[1:]

In [21]:
data1=data[12:]

In [32]:
data1

['Ishan',
 'Kishan ',
 'India ',
 '2',
 'Crore ',
 '15.25',
 'Crore ',
 'Mumbai',
 'Indians   ',
 'Deepak',
 'Chahar ',
 'India ',
 '2',
 'Crore ',
 '14',
 'Crore ',
 'Chennai',
 'Super',
 'Kings   ',
 'Shreyas',
 'Iyer ',
 'India ',
 '2',
 'Crore ',
 '12.25',
 'Crore ',
 'Kolkata',
 'Knight',
 'Riders   ',
 'Liam',
 'Livingstone ',
 'England ',
 '1',
 'Crore ',
 '11.50',
 'Crore ',
 'Punjab',
 'Kings   ',
 'Shardul',
 'Thakur ',
 'India ',
 '2',
 'Crore ',
 '10.75',
 'Crore ',
 'Delhi',
 'Capitals   ',
 'Harshal',
 'Patel ',
 'India ',
 '2',
 'Crore ',
 '10.75',
 'Crore ',
 'Royal',
 'Challengers',
 'Bangalore   ',
 'Wanindu',
 'Hasaranga ',
 'Sri',
 'Lanka ',
 '1',
 'Crore ',
 '10.75',
 'Crore ',
 'Royal',
 'Challengers',
 'Bangalore   ',
 'Nicholas',
 'Pooran ',
 'West',
 'Indies ',
 '1.50',
 'Crore ',
 '10.75',
 'Crore ',
 'Sunrisers',
 'Hyderabad   ',
 'Prasidh',
 'Krishna ',
 'India ',
 '1',
 'Crore ',
 '10',
 'Crore ',
 'Rajasthan',
 'Royals   ',
 'Lockie',
 'Ferguson ',
 'New',
 'Zealand ',
 '2',
 'Crore ',
 '10',
 'Crore ',
 'Gujarat',
 'Titans   ',
 'Avesh',
 'Khan ',
 'India ',
 '20',
 'Lakhs ',
 '10',
 'Crore ',
 'Lucknow',
 'Super',
 'Giants   ',
 'Kagiso',
 'Rabada ',
 'South',
 'Africa ',
 '2',
 'Crore ',
 '9.25',
 'Crore ',
 'Punjab',
 'Kings   ',
 'Rahul',
 'Tewatia ',
 'India ',
 '40',
 'Lakh ',
 '9',
 'Crore ',
 'Gujarat',
 'Titans   ',
 'Shahrukh',
 'Khan ',
 'India ',
 '40',
 'Lakh ',
 '9',
 'Crore ',
 'Punjab',
 'Kings   ',
 'Jason',
 'Holder ',
 'West',
 'Indies ',
 '1.50',
 'Crore ',
 '8.75',
 'Crore ',
 'Lucknow',
 'Super',
 'Giants   ',
 'Washington',
 'Sundar ',
 'India ',
 '1.50',
 'Crore ',
 '8.75',
 'Crore ',
 'Sunrisers',
 'Hyderabad   ',
 'Shimron',
 'Hetmyer ',
 'West',
 'Indies ',
 '1.50',
 'Crore ',
 '8.50',
 'Crore ',
 'Rajasthan',
 'Royals   ',
 'Rahul',
 'Tripathi ',
 'India ',
 '40',
 'Lakh ',
 '8.50',
 'Crore ',
 'Sunrisers',
 'Hyderabad   ',
 'Tim',
 'David ',
 'Australia ',
 '40',
 'Lakh ',
 '8.25',
 'Crore ',
 'Mumbai',
 'Indians   ',
 'Shikhar',
 'Dhawan ',
 'India ',
 '2',
 'Crore ',
 '8.25',
 'Crore ',
 'Punjab',
 'Kings   ',
 'Krunal',
 'Pandya ',
 'India ',
 '2',
 'Crore ',
 '8.25',
 'Crore ',
 'Lucknow',
 'Super',
 'Giants   ',
 'Jofra',
 'Archer ',
 'England ',
 '2',
 'Crore ',
 '8',
 'Crore ',
 'Mumbai',
 'Indians   ',
 'Trent',
 'Boult ',
 'New',
 'Zealand ',
 '2',
 'Crore ',
 '8',
 'Crore ',
 'Rajasthan',
 'Royals   ',
 'Nitish',
 'Rana ',
 'India ',
 '1',
 'Crore ',
 '8',
 'Crore ',
 'Kolkata',
 'Knight',
 'Riders   ',
 'Devdutt',
 'Padikkal ',
 'India ',
 '2',
 'Crore ',
 '7.75',
 'Crore ',
 'Rajasthan',
 'Royals   ']

In [35]:
player_names=[]

In [36]:
k=0
string=""

for i in range(0,len(data1)):
    if(k<=1):
        string+=data1[i]
        k+=1
    if(k==2):
        player_names.append(string)
        k+=1
    
    if(k==8):
        string=""
        k=0
    k+=1

In [37]:
player_names

['Ishan',
 'Crore ',
 'India ',
 'Chennai',
 'India ',
 'Kolkata',
 'England ',
 'Punjab',
 '2',
 'Capitals   ',
 'Crore ',
 'Bangalore   ',
 '1',
 'Challengers',
 'Indies ',
 'Sunrisers',
 '1',
 'Royals   ',
 '2',
 'Titans   ',
 'Lakhs ',
 'Giants   ',
 '2',
 'Kings   ',
 'Lakh ',
 'Shahrukh',
 '9',
 'Holder ',
 '8.75',
 'Washington',
 '8.75',
 'Hetmyer ',
 '8.50',
 'Tripathi ',
 'Crore ',
 'Australia ',
 'Mumbai',
 '2',
 'Kings   ',
 'Crore ',
 'Giants   ',
 'Crore ',
 'Trent',
 'Crore ',
 'Nitish',
 '8',
 'Devdutt',
 '7.75']